version: '3'
services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=postgres://maria:xsm3FiDNfze1@twilight-paper-812693.us-east-2.aws.neon.tech/neondb?options=project%3Dtwilight-paper-812693&sslmode=require
