version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"    
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
    links:
      - app